name: learn-github-actions
on: 
  push:
    branches: [ main ]
  pull_request: 
    branches: [ main ]
  
jobs:
  check-bats-version:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '16'
      - name: Install dependencies
        run: npm ci
      - run: npm run test
